[config]
reload_apps = true

scheme = "vibrant"
contrast = "high"

[overrides.primary]
saturation = 3

[overrides.secondary]
saturation = 2

[overrides.tertiary]
saturation = 1.4


[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland.conf"
output_path = "~/.config/hypr/colors.conf"