[config]
reload_apps = true


[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland.lua"
output_path = "~/.config/hypr/colors.lua"

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar.css"
output_path = "~/.config/waybar/colors.css"

[templates.rofi]
input_path = "~/.config/matugen/templates/custom.rasi"
output_path = "~/.config/rofi/custom.rasi"
