#!/bin/sh

notify-send -t 1500 -u low -- "GPU Screen Recorder" "Started recording replay"

nohup gpu-screen-recorder -w screen -a "default_input|default_output|app-inverse:steam" -f 60 -r 30 -c mp4 -o $HOME/Videos > $HOME/.bin/gpu-logs.txt 2>&1 &

disown
