listener {
	timeout = 600                                # 2.5min.
	on-timeout = hyprctl dispatch dpms off
	on-resume = hyprctl dispatch dpms on
	ignore_dbus_inhibit = false 
	ignore_systemd_inhibit = false
}
