windowrule {
	name = kitty-center
	match:class = ^kitty.center*
	float = on
	center = on
	size = 900 500
}

windowrule {
	name = bitwarden-center
	match:title = ^*.?Bitwarden
	opacity = 0.2
	float = on
	center = on
	size = 900 500
}
windowrule {
	name = minecraft-monitor
	match:class = ^Minecraft.*
	monitor = DP-2
}

windowrule {
	name = steam-monitor
	match:class = ^steam_app_.*
	monitor = DP-2
}

windowrule {
  name = windowrule-1
  match:title = Steam
  tile = on
}

windowrule {
  name = windowrule-2
  match:title = ^()$
  match:class = ^(steam)$
  stay_focused = on
  min_size = 1 1
}

# Ignore maximize requests from apps. You'll probably like this.
windowrule {
  name = windowrule-3
  suppress_event = maximize
  match:class = .*
}


# Fix some dragging issues with XWayland
windowrule {
  name = windowrule-4
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}

layerrule {
  name = layerrule-1
  blur = on
  ignore_alpha = 0
  xray = 0
  match:namespace = notifications
}